# batch_sizes: [8, 16, 32, 64, 128]
batch_sizes: [50]
device: cuda
model: inr-gan
num_warmup_iters: 10
num_profile_iters: 25

# Set to >0 if you want to enable mixed precision training
# StyleGAN2-ADA uses num_fp16_res=4
num_fp16_res: 0
